spring:
    application:
        name: backend-entrega3
    jpa:
        database: POSTGRESQL
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://localhost:5432/tingeso3
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver
    sql:
        init:
            mode: always
server:
    port: 8080